### ISSUE TITLE
GitPython environment not modified properly

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1247]
During a git push from within `publish`:
````
[DEBUG  ] Running: ['ssh', '-O', 'check', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/747501b3584c118d95811f2c756f2a9f', 'kumo.ovgu.de']
| cwd: None 
[ERROR  ] Cmd('git') failed due to: exit code(128)
|   cmdline: git -c receive.autogc=0 -c gc.auto=0 push --porcelain target1 git-annex:git-annex
|   stderr: 'fatal: bad numeric config value 'updateInstead' for 'receive.denycurrentbranch' in config: invalid unit
| fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.' [cmd.py:wait:291] (GitCommandError) 
````

system-git on that host is old. However, it should have been done with GIT_SSH_COMMAND='datalad ssrun'. But from some reason it is not happening (code is on top of #1241). Running this manually works:

````
% GIT_SSH_COMMAND='datalad sshrun' GIT_TRACE=1 git -c receive.autogc=0 -c gc.auto=0 push --porcelain target1 git-annex:git-annex
21:06:19.174577 git.c:371               trace: built-in: git 'push' '--porcelain' 'target1' 'git-annex:git-annex'
21:06:19.174855 run-command.c:350       trace: run_command: 'datalad sshrun' 'kumo.ovgu.de' 'git-receive-pack '\''public_html/demoannex'\'''
21:06:19.175065 run-command.c:209       trace: exec: '/bin/sh' '-c' 'datalad sshrun "$@"' 'datalad sshrun' 'kumo.ovgu.de' 'git-receive-pack '\''public_html/demoannex'\'''
To kumo.ovgu.de:public_html/demoannex
=	refs/heads/git-annex:refs/heads/git-annex	[up to date]
Done
````

**Comment by mih** [comment]
Adding:

````
import os
os.environ['GIT_SSH_COMMAND'] = "datalad sshrun"
````

doesn't change a things -- as @bpoldrack predicted.

**Comment by bpoldrack** [comment]
Figured it out with @mih. Fix included in #1237.

In case we need a reminder when we run into a similar thing:
Key issue was, that we share connections with annex. Therefore in the case annex (instead of datalad) creates the connection to be used, remote sensing of annex_install_dir wasn't done. So `datalad sshrun` was called, but didn't lead to `SSHConnection` passing the corrected `PATH` to the remote command.

**Comment by mih** [comment]
Thinking about this more: I assume that any annex command that executes remote git calls would make an attempt to run its own bundled Git -- if any exists. If that is the case, this is nothing to worry about. However, if that is not the case, we should make an effort to open connections ourselves.

**Comment by bpoldrack** [comment]
I kind of agree.
However, this would probably not be about opening the connection anymore (since this is fixed now), but about executing git-annex calls the same way (via `datalad sshrun`).

I'll try to examine this to be sure.

**Comment by bpoldrack** [comment]
Looking into it, I think we need to use `datalad sshrun` with annex, too.
With `annex sync` for example I used `GIT_SSH_COMMAND="cat"` in order to see what is passed to it and this is plain `git-upload-pack`, `git-receive-pack`. No `PATH`passed or `sendenv` used.

**Comment by bpoldrack** [comment]
BTW: The above mentioned might be the issue, leading to several failures in PR #1237 , where system-git is used that is too old for `config receive.denyCurrentBranch updateInstead`

**Comment by mih** [comment]
Damn

https://travis-ci.org/datalad/datalad/jobs/197904584

This actually happens (at least for one test) in a GitRepo.push() call, that should really really not result in a system-git call. It seems it is still not working on travis.

**Comment by mih** [comment]
Ok, this:

https://github.com/datalad/datalad/pull/1237/commits/6794e9d6761bbed123cfe506448fa2f9deb98162

hopefully makes git annex use sshrun for most (if not all) cases.

**Comment by bpoldrack** [comment]
Brutal approach but might work ;-)

**Comment by bpoldrack** [comment]
Okay, for one thing the title doesn't describe the actual issue correctly and furthermore this seems to be solved for now.
Thus - closing.
