### ISSUE TITLE
publish not clever enough for my taste

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#400]
````
/tmp/mine (git)-[master] % datalad publish testpublic
2016-04-11 14:54:04,484 [ERROR  ] insufficient information for publication (needs at least a dataset or a path [publish.py:__call__:116] (ValueError) (main.py:223)
````

`/tmp/mine` is a directory containing a dataset with a configured `testpublic` sibling.

**Comment by bpoldrack** [comment]
That should work, indeed.

**Comment by bpoldrack** [comment]
Fixed in https://github.com/datalad/datalad/pull/388/commits/168a50434c8524e86efa81fbb7098a59bd759ecf

**Comment by hanke** [comment]
````
% datalad publish testpublic2 
2016-04-11 15:35:30,287 [ERROR  ] stderr| fatal: No path specified. See 'man git-pull' for valid url syntax (cmd.py:351)
2016-04-11 15:35:30,287 [ERROR  ] Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'push', 'testpublic2', 'master'] under '/tmp/mine'. Exit code=128. out= err=fatal: No path specified. See 'man git-pull' for valid url syntax
|  (cmd.py:295)
2016-04-11 15:35:30,288 [ERROR  ] CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'push', 'testpublic2', 'master']' failed with exitcode 128.
| Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'push', 'testpublic2', 'master'] under '/tmp/mine'. Exit code=128. out= err=fatal: No path specified. See 'man git-pull' for valid url syntax
|  [cmd.py:run:296] (CommandError) (main.py:223)
````

**Comment by hanke** [comment]
Reusing this issue as the title still matches:

````
% datalad create-publication-target-sshwebserver ssh://localhost/tmp/remote3 testpublic3
mih@localhost's password: 
 (cmd.py:351):54:12,516 [ERROR  ] stderr| Stop listening request sent.
````

Complains loudly but issue does not seem to have practical relevance.

And later

````
% datalad publish testpublic3
mih@localhost's password: 
mih@localhost's password: 
````

asks for passwd twice.

**Comment by bpoldrack** [comment]
Irrelevant log message removed.

leaving it open as a reminder to use socket for ssh with publish command.

**Comment by hanke** [comment]
FTR: None of the reported issues remained when testing today's #435.

Ready to close from my PoV.

**Comment by yarikoptic** [comment]
added closes statement to #435 so hopefully soon it will come out from under WiP umbrella?
