### ISSUE TITLE
No canonical way to add an existing RIA remote, users readig the manual/help pages are lead into broken situations

### ISSUE THREAD

**Issue by mlell** [datalad/datalad#7543]
### What is the problem?

Given you have a RIA remote and clone from it a dataset A. Now, from A, clone a dataset B. Dataset B does not have the RIA remote enabled and there is no way to do it without manually setting up various `git config` settings. 

Users trying to do this will probably try two ways, both of which lead to a broken situation with multiple annex UUIDs assigned to the same folder, which is a recipe for data loss (as git annex'es numcopies saveguard is fooled by this):
* manually using `git remote add ...` and `git annex enableremote`: This leads to a git annex message telling the user that the RIA remote is probably broken and they should reinitialize it. If they follow this advice, they ruin the format of the RIA store: 
```    
Remote origin: This repository is not initialized for use by git-annex, but /test/datalad-ria-addremote/ria/20d/da232-002f-4e09-90b6-62924a994136/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.
```
* Running `datalad create-sibling-ria --existing=reconfigure`. This does not just add the RIA remote but modifies assigns a new annex UUID to the RIA store, which is a dangerous option. The RIA store then has **two** annex UUIDs in its config! I do not see any use for that, at the very least I think this option should be called `--reckless reconfigure` or similar, as for dangerous commands elsewhere
* The only way is to use the manual way but not follow the error messages but call `git config` several times to recreate the desired configuration. Only users with in-depth knowledge of git annex and the RIA format can do this, i.e. only datalad developers, certainly not the user base I think datalad targets (scientists that are not familiar with the datalad codebase)

### What steps will reproduce the problem?

Follow this script:

```sh

```
set -ue

# Example repository
datalad create a
cd a
echo "hello" > file
datalad save
id="$(git config -f .datalad/config datalad.dataset.id)"
riadir="${id::3}/${id:3}"

# Set up and sync the RIA store
datalad create-sibling-ria --new-store-ok -s ria ria+file://$PWD/../ria
datalad push --to ria
cd ..
datalad clone ria+file://$PWD/ria#$id b
datalad clone ria+file://$PWD/ria#$id c

# Dump the configurations for comparison
git -C a config --get-regexp remote | sort > a-create-ria.config
git -C b config --get-regexp remote | sort > b-clone-ria.config
git -C ria/$riadir config --list --local| sort > ria1.config

## Now simulate that we do not have the ria store initialized. Either
# we deleted it or we cloned another copy of the repo and not directly
# from the RIA store
cd b
git remote remove origin
git remote remove ria-storage

# First attempt: manually add
git remote add origin "$(realpath  ../ria/$riadir)"
git annex enableremote ria-storage
git config --get-regexp remote | sort > ../b-add-manual.config

# Config is erroneous
cd ..
diff -ud b-clone-ria.config b-add-manual.config > b-add-manual.diff || true
# Try --existing=reconfigure
cd c
git remote remove origin
git remote remove ria-storage

datalad create-sibling-ria --existing=reconfigure -s ria-new ria+file://$PWD/../ria

cd ..
git -C c config --get-regex remote | sort > c-after-reconfig.config
diff -ud b-clone-ria.config c-after-reconfig.config > c-after-reconfig.diff || true
pwd
git -C ria/$riadir config --list --local| sort > ria-after-reconfig.config
diff -ud ria1.config ria-after-reconfig.config > ria-after-reconfig.diff || true

####### ignoreannex of RIA git remote
cat b-add-manual.diff

####### chaos
cat ria-after-reconfig.diff

```

### DataLad information

_No response_

### Additional context

_No response_

### Have you had any success using DataLad before?

_No response_

**Comment by oesteban** [comment]
I believe I have a related question - please let me know if I should open a new issue (and delete this message here) if this report is totally different.

In my case, I created a dataset with a `github` remote and a "ria+ssh://" (storage only) called `ria-storage` pointing at a path on my cluster's storage filesystem.

From outside, this has been working wonderfully, and I have my dataset in sync from several systems, I've pushed from several systems... but always from outside the cluster.

From inside the cluster I have a big problem: the `ria-storage` remote cannot be accessed anymore. Instead, I would like to configure a "ria+file://" remote pointing at the same path above.

I haven't found a way of doing this. I can confirm that `datalad create-sibling-ria --existing=reconfigure` does not seem to have any positive outcome.

How should I configure the remotes and/or siblings so that I can directly access the annexed files from within the cluster?

**Comment by mlell** [comment]
@oesteban I think your issue is a bit different, because you want to manually change the configuration of the sibling pair (git and storage) whereas here the problem is that users can inadvertently crate a non-standard situation and datalad does not fix it. 

For your issue, if you are proficient with the `git annex` internals of datalad, and if your git annex version is recent enough,, you could take a look on the [`git annex initremote --sameas`](https://git-annex.branchable.com/tips/multiple_remotes_accessing_the_same_data_store/) option. Maybe you can create a git annex special remote with the alternative path this way. Maybe you can also use the [`--private`](https://git-annex.branchable.com/tips/cloning_a_repository_privately/) option if you do not want other siblings outside of the cluster to take up the `file://` path that is only valid inside the cluster

**Comment by oesteban** [comment]
@mlell indeed -- thanks for the pointer. I have successfully resolved the problem:

```
git annex initremote --sameas=ria-storage curnagl-storage type=external externaltype=ora encryption=none url="ria+file://<local-path-on-cluster>"
```
